import { Toaster } from "react-hot-toast";
import NavBar from "./components/site/NavBar";
import { AuthProvider } from "./context/authContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="" data-theme="dark">
        <AuthProvider>
          <NavBar />
          <Toaster />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
